type tech = { id: string, name: string, ref: string };
export const technologies: tech[] = [
    {id: "nextjs", name: "NextJS", ref: "https://nextjs.org/"},
    {id: "react", name: "React", ref: "https://reactjs.org/"},
    {id: "tailwind", name: "Tailwind", ref: "https://tailwindcss.com/"},
    {id: "php", name: "PHP", ref: "https://www.php.net/"},
    {id: "wordpress", name: "WordPress", ref: "https://wordpress.org/"},
    {id: "nodejs", name: "NodeJS", ref: "https://nodejs.org/en/"},
    {id: "mysql", name: "MySQL", ref: "https://www.mysql.com/"},
    {id: "mongodb", name: "MongoDB", ref: "https://www.mongodb.com/"},
    {id: "git", name: "Git", ref: "https://git-scm.com/"},
    {id: "github", name: "GitHub", ref: "http://github.com/"},
    {id: "vscode", name: "VSCode", ref: "https://code.visualstudio.com/"},
    {id: "figma", name: "Figma", ref: "https://www.figma.com/"},
    {id: "photoshop", name: "Photoshop", ref: "https://www.adobe.com/products/photoshop.html"},
    {id: "supabase", name: "Supabase", ref: "https://supabase.io/"},
    {id: "vercel", name: "Vercel", ref: "https://vercel.com/"},
    {id: "netlify", name: "Netlify", ref: "https://www.netlify.com/"},
    {id: "heroku", name: "Heroku", ref: "https://www.heroku.com/"},
    {id: "firebase", name: "Firebase", ref: "https://firebase.google.com/"},
    {id: "cloudflare", name: "Cloudflare", ref: "https://www.cloudflare.com/"},
    {id: "digitalocean", name: "DigitalOcean", ref: "https://www.digitalocean.com/"},
    {id: "aws", name: "AWS", ref: "https://aws.amazon.com/"},
    {id: "framer-motion", name: "Framer Motion", ref: "https://www.framer.com/motion/"},
    {id: "Strapi", name: "Strapi", ref: "https://strapi.io/"},
    {id: "graphql", name: "GraphQL", ref: "https://graphql.org/"},
    {id: "typescript", name: "Typescript", ref: "https://www.typescriptlang.org/"},
    {id: "javascript", name: "Javascript", ref: "https://www.javascript.com/"},
    {id: "html", name: "HTML", ref: "https://html.com/"},
    {id: "css", name: "CSS", ref: "https://www.w3.org/Style/CSS/Overview.en.html"},
    {id: "sass", name: "Sass", ref: "https://sass-lang.com/"},
    {id: "stripe", name: "Stripe", ref: "https://stripe.com/"},
    {id: "styled-components", name: "Styled Components", ref: "https://styled-components.com/"},
    {id: "python", name: "Python", ref: "https://www.python.org/"},
    {id: "c", name: "C", ref: "https://en.wikipedia.org/wiki/C_(programming_language)"},
    {id: "c++", name: "C++", ref: "https://en.wikipedia.org/wiki/C%2B%2B"},
    {id: "c#", name: "C#", ref: "https://docs.microsoft.com/en-us/dotnet/csharp/"},
    {id: "java", name: "Java", ref: "https://www.java.com/en/"},
    {id: "rust", name: "Rust", ref: "https://www.rust-lang.org/"},
    {id: "sanity", name: "Sanity", ref: "https://www.sanity.io/"},
    {id: "gatsby", name: "Gatsby", ref: "https://www.gatsbyjs.com/"},
    {id: "threejs", name: "ThreeJS", ref: "https://threejs.org/"},
    {id: "nextauth", name: "NextAuth", ref: "https://next-auth.js.org/"},
    {id: "jquery", name: "jQuery", ref: "https://jquery.com/"},
    {id: "phaserjs", name: "PhaserJS", ref: "https://phaser.io/"},
    {id: "expressjs", name: "ExpressJS", ref: "https://expressjs.com/"},
    {id: "socketio", name: "SocketIO", ref: "https://socket.io/"},
    {id: "reactnative", name: "React Native", ref: "https://reactnative.dev/"},
    {id: "vite", name: "Vite", ref: "https://vitejs.dev/"},
    {id: "svelte", name: "Svelte", ref: "https://svelte.dev/"},
    {id: "astro", name: "Astro", ref: "https://astro.build/"},
    {id: "postgresql", name: "PostgreSQL", ref: "https://www.postgresql.org/"},
    {id: "redis", name: "Redis", ref: "https://redis.io/"},
    {id: "docker", name: "Docker", ref: "https://www.docker.com/"},
    {id: "sqlite", name: "SQLite", ref: "https://www.sqlite.org/index.html"},
    {id: "Markdown", name: "Markdown", ref: "https://www.markdownguide.org/"},
    {id: "deno", name: "Deno", ref: "https://deno.land/"},
    {id: "daisyui", name: "DaisyUI", ref: "https://daisyui.com/"},
    {id: "shadcn/ui", name: "Shadcn/UI", ref: "https://www.github.com/shadcn/ui/"},
    {id: "prisma", name: "Prisma", ref: "https://www.prisma.io/"},


];
