/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/pawn.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pawn-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pawn_White_0.geometry} material={materials.White} position={[3.919, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={113.95} />
    </group>
  )
}

useGLTF.preload('/pawn-transformed.glb')
