/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 ./public/salmon.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/salmon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Salmon.geometry} material={materials.skin} rotation={[1.377, -0.107, 0.496]} />
    </group>
  )
}

useGLTF.preload('/salmon-transformed.glb')
